"""Real Minnesota city/county/ZIP combinations.

These are genuine MN geographic facts (city, county, ZIP), used only to pick
a realistic city/county/ZIP combination for a fictional address. Street-level
detail (house number, street name) is always synthetic -- see
generator/entities.py. No real individual or organization is associated with
any address generated by this toolkit.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class MNCity:
    city: str
    county: str
    zip5: str
    region: str  # "metro" | "duluth" | "rochester" | "outstate"


MN_CITIES: tuple[MNCity, ...] = (
    # Twin Cities metro
    MNCity("Minneapolis", "Hennepin", "55401", "metro"),
    MNCity("Minneapolis", "Hennepin", "55407", "metro"),
    MNCity("St. Paul", "Ramsey", "55101", "metro"),
    MNCity("St. Paul", "Ramsey", "55106", "metro"),
    MNCity("Bloomington", "Hennepin", "55431", "metro"),
    MNCity("Plymouth", "Hennepin", "55441", "metro"),
    MNCity("Maple Grove", "Hennepin", "55369", "metro"),
    MNCity("Eagan", "Dakota", "55121", "metro"),
    MNCity("Woodbury", "Washington", "55125", "metro"),
    MNCity("Brooklyn Park", "Hennepin", "55443", "metro"),
    MNCity("Coon Rapids", "Anoka", "55433", "metro"),
    MNCity("Burnsville", "Dakota", "55337", "metro"),
    MNCity("Apple Valley", "Dakota", "55124", "metro"),
    MNCity("St. Cloud", "Stearns", "56301", "metro"),
    # Duluth
    MNCity("Duluth", "St. Louis", "55802", "duluth"),
    MNCity("Duluth", "St. Louis", "55811", "duluth"),
    MNCity("Hermantown", "St. Louis", "55811", "duluth"),
    # Rochester
    MNCity("Rochester", "Olmsted", "55901", "rochester"),
    MNCity("Rochester", "Olmsted", "55902", "rochester"),
    MNCity("Byron", "Olmsted", "55920", "rochester"),
    # Outstate MN
    MNCity("Mankato", "Blue Earth", "56001", "outstate"),
    MNCity("Moorhead", "Clay", "56560", "outstate"),
    MNCity("Willmar", "Kandiyohi", "56201", "outstate"),
    MNCity("Bemidji", "Beltrami", "56601", "outstate"),
    MNCity("Fergus Falls", "Otter Tail", "56537", "outstate"),
    MNCity("Marshall", "Lyon", "56258", "outstate"),
    MNCity("Worthington", "Nobles", "56187", "outstate"),
    MNCity("Hibbing", "St. Louis", "55746", "outstate"),
    MNCity("Albert Lea", "Freeborn", "56007", "outstate"),
    MNCity("Red Wing", "Goodhue", "55066", "outstate"),
    MNCity("Winona", "Winona", "55987", "outstate"),
    MNCity("Brainerd", "Crow Wing", "56401", "outstate"),
    MNCity("International Falls", "Koochiching", "56649", "outstate"),
    MNCity("New Ulm", "Brown", "56073", "outstate"),
    MNCity("Alexandria", "Douglas", "56308", "outstate"),
)

STREET_SUFFIXES = ("St", "Ave", "Dr", "Ln", "Rd", "Ct", "Way", "Trail")
STREET_NAMES = (
    "Maple", "Oak", "Cedar", "Birch", "Lakeview", "Northstar", "Prairie",
    "River", "Hilltop", "Sunset", "Pine", "Aspen", "Heron", "Meadow",
    "Tamarack", "Bluff", "Loon", "Cardinal",
)
