"""Generate docs/RULE_SOURCE_TRACE.md from registered validator rules.

Run from repo root:
    python scripts/generate_rule_source_trace.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from mn_encounter_toolkit.validator.layer1_envelope import LAYER1  # noqa: E402
from mn_encounter_toolkit.validator.layer2_syntax import LAYER2  # noqa: E402
from mn_encounter_toolkit.validator.layer3_dhs_rules import LAYER3  # noqa: E402
from mn_encounter_toolkit.validator.layer4_consistency import LAYER4  # noqa: E402
from mn_encounter_toolkit.validator.rule_registry import RuleInfo  # noqa: E402

OUT = ROOT / "docs" / "RULE_SOURCE_TRACE.md"
ANNOTATED_PDF = "docs/reference/annotated/dhs_837_encounter_companion_guide_annotated.pdf"
DHS_PDF = "docs/reference/dhs_837_encounter_companion_guide.pdf"

SUPPLEMENTAL_TRACES = [
    {
        "rule_id": "DEFAULT-SEPARATORS (ISA11)",
        "layer": "Writer / parser defaults",
        "description": "Default repetition separator `[` for DHS-targeted output.",
        "source_citation": (
            "dhs_837_encounter_companion_guide.pdf p.35 (ISA11) — "
            "'REPETITION SEPARATOR -- PLEASE SEND DHS '['."
        ),
        "code": "edi/x12_core.py — Separators dataclass",
    },
]


def _module_path(rule: RuleInfo) -> str:
    mod = rule.func.__module__.replace("mn_encounter_toolkit.", "")
    return "src/mn_encounter_toolkit/" + mod.replace(".", "/") + ".py"


def _func_name(rule: RuleInfo) -> str:
    return rule.func.__name__


def _pages_from_citation(citation: str | None) -> str:
    if not citation:
        return "—"
    pages: set[int] = set()
    for start, end in re.findall(r"p\.(\d+)-(\d+)", citation):
        pages.update(range(int(start), int(end) + 1))
    for page in re.findall(r"p\.(\d+)", citation):
        pages.add(int(page))
    return ", ".join(f"p.{p}" for p in sorted(pages)) if pages else "—"


def _rule_section(rule: RuleInfo) -> list[str]:
    lines = [
        f"#### `{rule.rule_id}`",
        "",
        f"- **Layer:** {rule.layer}",
        f"- **Description:** {rule.description}",
        f"- **Code:** `{_module_path(rule)}` → `{_func_name(rule)}`",
    ]
    if rule.source_citation:
        lines.append(f"- **Source citation:** {rule.source_citation}")
        lines.append(f"- **PDF pages (cited):** {_pages_from_citation(rule.source_citation)}")
    else:
        lines.append("- **Source citation:** *(none — base X12 or internal invariant)*")
    lines.append("")
    return lines


def _layer_table(rules: list[RuleInfo]) -> list[str]:
    lines = [
        "| Rule ID | PDF pages | Has source citation |",
        "|---------|-----------|---------------------|",
    ]
    for rule in rules:
        pages = _pages_from_citation(rule.source_citation)
        cited = "Yes" if rule.source_citation else "No"
        lines.append(f"| `{rule.rule_id}` | {pages} | {cited} |")
    lines.append("")
    return lines


def build_markdown() -> str:
    l1, l2, l3, l4 = LAYER1.rules(), LAYER2.rules(), LAYER3.rules(), LAYER4.rules()
    lines = [
        "# Rule source traceability",
        "",
        "Maps each validation rule to the **source document language** (or internal scope) "
        "used to implement it. Generated by `scripts/generate_rule_source_trace.py` from "
        "registered rule metadata — re-run after changing `layer*_*.py`.",
        "",
        f"**Primary PDF:** [`{DHS_PDF}`](reference/dhs_837_encounter_companion_guide.pdf)  ",
        f"**Annotated copy (highlights):** [`{ANNOTATED_PDF}`](reference/annotated/dhs_837_encounter_companion_guide_annotated.pdf)",
        "",
        "Layer 2 rules follow base X12 TR3 (`mucg_837p.pdf` as secondary, not encounter authority). "
        "Layer 4 rules are toolkit cross-field invariants with no external PDF citation.",
        "",
        "---",
        "",
        "## Summary",
        "",
        "| Layer | Rules | PDF-backed |",
        "|-------|------:|-----------:|",
        f"| 1 Envelope | {len(l1)} | {sum(1 for r in l1 if r.source_citation)} |",
        f"| 2 Syntax | {len(l2)} | 0 |",
        f"| 3 DHS business | {len(l3)} | {sum(1 for r in l3 if r.source_citation)} |",
        f"| 4 Consistency | {len(l4)} | 0 |",
        "",
        "---",
        "",
        "## Layer 1 — Envelope",
        "",
        *_layer_table(l1),
    ]
    for rule in l1:
        if rule.source_citation:
            lines.extend(_rule_section(rule))

    lines.extend(
        [
            "---",
            "",
            "## Layer 2 — Base X12 / TR3 syntax",
            "",
            "**Authority:** X12 005010X222A1 / 005010X223A2; see `mucg_837p.pdf` for FFS syntax reference only "
            "(not DHS encounter authority per landing page).",
            "",
            *_layer_table(l2),
            "---",
            "",
            "## Layer 3 — DHS encounter business rules",
            "",
            "**Authority:** `dhs_837_encounter_companion_guide.pdf` — each finding includes `SOURCE:` in output.",
            "",
            *_layer_table(l3),
        ]
    )
    for rule in l3:
        lines.extend(_rule_section(rule))

    lines.extend(
        [
            "---",
            "",
            "## Layer 4 — Cross-field consistency",
            "",
            "Internal consistency checks on parsed claim data — not traced to an external PDF.",
            "",
            *_layer_table(l4),
            "---",
            "",
            "## Supplemental DHS mappings (writer / defaults)",
            "",
        ]
    )
    for item in SUPPLEMENTAL_TRACES:
        lines.extend(
            [
                f"#### `{item['rule_id']}`",
                "",
                f"- **Scope:** {item['layer']}",
                f"- **Description:** {item['description']}",
                f"- **Source citation:** {item['source_citation']}",
                f"- **Code:** `{item['code']}`",
                "",
            ]
        )

    lines.extend(
        [
            "---",
            "",
            "## Response generators (module-level)",
            "",
            "| Component | Primary source | Code |",
            "|-----------|----------------|------|",
            "| 999 deterministic | `mucg_999_ta1.pdf` + X12 005010X231; runs Layer 1–2 on input | `response/gen_999.py` |",
            "| 835E | `mucg_835.pdf` Sec 2.4 / Appendix C (adaptation — see `KNOWN_LIMITATIONS.md`) | `response/gen_835e.py` |",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    OUT.write_text(build_markdown(), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
